source 'https://rubygems.org'

ruby '2.0.0'

gem 'aasm'
gem 'airbrake'
gem 'apartment', '~> 0.24.3'
gem 'awesome_nested_set', '3.0.0.rc.2'
gem 'dalli'
gem 'haml-rails'
gem 'mysql2', '~> 0.3.15'
gem 'newrelic_rpm'
gem 'paranoia', '~> 2.0'
gem 'rabl'
gem 'rails', '~> 4.0.0'
gem 'unicorn'

group :development do
  gem 'annotate', ">=2.5.0"
  gem 'capistrano', '~> 2.0'
  gem 'guard'
  gem 'guard-rspec'
  gem 'pry-rails', '~> 0.3.2'
  gem 'pry-nav'
  gem 'terminal-notifier-guard'
end

group :development, :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'guard-rubocop'
  gem 'rspec-rails', '~> 2.0'
  gem 'rubocop'
end
